### ISSUE TITLE
Session驱动似乎还是文件读写

### ISSUE THREAD

**Issue by MikeChongCan** [chekun/laravel4sae#12]
```
ErrorException  
file_put_contents(/data1/www/htdocs/698/sdufe/1/app/storage/sessions/97d86cf409670436ec1550df428650853f9659e2) [<a href='function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: Permission denied
```

http://sdufe.sinaapp.com

我在 app/config/app.php 里测试了下 `if (defined('SAE_ACCESSKEY') && (substr(SAE_ACCESSKEY, 0, 4 ) != 'kapp'))` 确实为 `TRUE` ，但是不知道为何没有调用扩展的Session实现

http://laravel4sae.sinaapp.com/ 的源码是否能提供个打包下载，自己弄的好郁闷

**Comment by chekun** [comment]
这个你配置文件没有改。session要指定驱动为memcache
仔细看：https://github.com/chekun/laravel4sae/blob/master/HOW-TO.md

**Comment by MikeChongCan** [comment]
Thanks for your respond.

不好意思，只copy了/confing/app.php的内容。
