### ISSUE TITLE
本地应该用什么环境开发？miniSAE？

### ISSUE THREAD

**Issue by MikeChongCan** [chekun/laravel4sae#13]
我现在还是在用很旧的miniSAE开发，不知道有没有sae的vagrant环境。

如果直接在系统里运行感觉也不好，毕竟很多线上服务不好模拟。

**Comment by chekun** [comment]
这个package的开发目的是就是简化本地开发，一般来说本地开发就是本地开发无需理会sae线上服务，这个就是这个package的终极目标，当然还需进一步开发一些模块，在这些模块还没有完全到位的情况下，可以进行分化处理。
也就是：

```
if (is_sae()) {

} else {

}
```

**Comment by MikeChongCan** [comment]
Thanks.

最近倒是打算尝试用vagrant写个SAE模拟环境。

**Comment by chekun** [comment]
Just Do It!
