### ISSUE TITLE
SAE已开放ini_set函数

### ISSUE THREAD

**Issue by smallcode** [chekun/laravel4sae#15]
我测试了一下，可以。请你再确认一下。

信息来源：http://cloudbbs.org/forum.php?mod=viewthread&tid=22019&page=3#pid142482

**Comment by smallcode** [comment]
仍然会出现：
Warning: Set the ini directive 'mbstring.script_encoding' without permission

**Comment by hujoker** [comment]
解了吗，我也会出现这个

**Comment by smallcode** [comment]
> 解了吗，我也会出现这个

解是解了。但设置字符集时还是会出错。具体原因不明。
