### ISSUE TITLE
新人不太懂,请教一下

### ISSUE THREAD

**Issue by pipiiiiii** [chekun/laravel4sae#18]
刚刚接触web,懂的不太多.我新建了一个laravel的空项目,用的是4.1.0版本的,和这个package的1.0.1版本,然后按照说明文档改过了.那个本地配置没有改,然后尝试在sae上运行public/index.php.出现Whoops, looks like something went wrong.不知道是否是设置有问题呢.麻烦了.

**Comment by chariothy** [comment]
hi, SAE上的KVDB打开了没有？另外，不要运行public/index.php，直接运行你的SAE主页，yoursite.sinaapp.com。

在 2014年11月4日 下午5:22，YanXinyu notifications@github.com写道：

> 刚刚接触web,懂的不太多.我新建了一个laravel的空项目,用的是4.1.0版本的,和这个package的1.0.1版本,然后按照说明文档改过了.那个本地配置没有改,然后尝试在sae上运行public/index.php.出现Whoops,
> looks like something went wrong.不知道是否是设置有问题呢.麻烦了.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chekun/laravel4sae/issues/18.

## 

##  Best regards

Henry Tian
田宏宇
技术支持组 http://192.168.22.142/wiki
Phone: +86 0523-80980018-8088
IP Extension: 283
江苏省泰州市杏林路12号G18幢

**Comment by pipiiiiii** [comment]
KVDB开了.那个我具体路由还没有写.主要想测试一下能否运行,我准备搭建的是一个基于laravel开发的CMS,所以先测试一下.

**Comment by chariothy** [comment]
我要下班了，这样，你把你的安装过程简要地列出来，我看看是否漏掉了哪一步。从在SAE创建项目开始。

在 2014年11月4日 下午6:13，YanXinyu notifications@github.com写道：

> KVDB开了.那个我具体路由还没有写.主要想测试一下能否运行,我准备搭建的是一个基于laravel开发的CMS,所以先测试一下.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chekun/laravel4sae/issues/18#issuecomment-61618558.

## 

##  Best regards

Henry Tian
田宏宇
技术支持组 http://192.168.22.142/wiki
Phone: +86 0523-80980018-8088
IP Extension: 283
江苏省泰州市杏林路12号G18幢

**Comment by pipiiiiii** [comment]
我是先在github上下载了一个4.1.0的laravel,在本地安装之后composer了一个1.0.1版本的laravel4sea,之后改的app.php,数据库连接也改过,存储方式也改了,就是那个配置本地开发版本的那个没有动.之后上传到了SAE上.我看您写的那个跟这个不太一样.我再试试您的那个

**Comment by pipiiiiii** [comment]
用了您的那个package已经成功,谢谢了

**Comment by chariothy** [comment]
不客气。
