### ISSUE TITLE
什么时候用 kvdb又什么时候用memcache

### ISSUE THREAD

**Issue by gantoday** [chekun/laravel4sae#19]
首先谢谢作者 给我们提供了很大的方便
我用了你的源码后 在sae后台统计 kvdb并没有使用
？可我看见文件夹下是有这个类的 想是我自己哪没搞清楚 故有此一问

**Comment by chariothy** [comment]
你好，你是说哪个类？如果量很少，可能后台统计看不出来。

在 2014年11月17日 下午3:46，肥龙哥哥 notifications@github.com写道：

> 首先谢谢作者 给我们提供了很大的方便
> 我用了你的源码后 在sae后台统计 kvdb并没有使用
> ？可我看见文件夹下是有这个类的 想是我自己哪没搞清楚 故有此一问
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/chekun/laravel4sae/issues/19.

## 

##  Best regards

Henry Tian
田宏宇
技术支持组 http://192.168.22.142/wiki
Phone: +86 0523-80980018-8088
IP Extension: 283
江苏省泰州市杏林路12号G18幢

**Comment by chekun** [comment]
Session 只会用到memcache
Cache 看你的配置，如果你配置了kvdb就会用，配置memcache了就用memecache哈。

**Comment by gantoday** [comment]
哦哦 那用哪个好呢 缓存
而且 配置是在config/cache吧

**Comment by chekun** [comment]
@gantoo 小网站其实都可以，kvdb收费便宜点，空间大一点。 :smiley:

**Comment by gantoday** [comment]
@chekun @chariothy 谢谢哈
