### ISSUE TITLE
无法找到SaePatcherServiceProvider

### ISSUE THREAD

**Issue by smallcode** [chekun/laravel4sae#2]
执行：php artisan sae:patch
出现错误：
PHP Fatal error:  Class 'Lavender\Cloud\Sina\Patcher\SaePatcherServiceProvider' not found
打开网页也出现以上错误。

**Comment by smallcode** [comment]
找到问题所在了：https://github.com/laravel/laravel/issues/2299
我用的是最新版本4.1

**Comment by smallcode** [comment]
用4.0.9版本也不行，可以执行：php artisan sae:patch，但是打开网页出现如下错误：

```
ErrorException
file_put_contents(/meta/services.json) [<a href='function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: Permission denied
```

**Comment by chekun** [comment]
@smallcode 亲，提示说你没有写那个文件的权限哈～～

**Comment by smallcode** [comment]
知道是无法写入文件（使用你的库不就是为了避免这个错误吗？）。我是按你的说明操作的，上传到SAE上了，怎么还会出现这个错误呢？

**Comment by chekun** [comment]
@smallcode 好的，我看下。

**Comment by smallcode** [comment]
你是否有打算升级到4.1版本呢？是的话，我等你出支持4.1版本的。

**Comment by chekun** [comment]
下午有空我来看下如何来兼容4.1哈。

**Comment by chekun** [comment]
@smallcode 已经解决

可以看这里。

http://laravel4sae.sinaapp.com/

**Comment by smallcode** [comment]
楼主真是神速呀。可以了。感谢！

**Comment by smallcode** [comment]
不好意思。发现新问题，当打开：http://laravel4sae.sinaapp.com/foo
会出现异常(貌似日志这块也得改改)：

```
Error in exception handler: 
The stream or file "/data1/www/htdocs/805/laravel4sae/1/app/storage/logs/laravel.log" 
could not be opened: fopen(/data1/www/htdocs/805/laravel4sae/1/app/storage/logs/laravel.log) [function.fopen]: 
failed to open stream: Permission denied in 
/data1/www/htdocs/805/laravel4sae/1/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:70
```

**Comment by chekun** [comment]
是的 如我在howto中所说的，目前只是解决了必须解决的部分，其他的希望大家贡献代码呀。呵呵。

**Comment by smallcode** [comment]
找到解决方法了，在app/start/global.php中注册一个异常处理器即可，例如：

```
App::missing(function($exception)
{
    return Response::make('页面不存在', 404);
});
```

**Comment by smallcode** [comment]
自从使用python后，再用回php就不习惯了。感觉还是python+django比较爽。

**Comment by chekun** [comment]
你这个不叫解决方法哈，anyway，这个issue先关了。
