### ISSUE TITLE
为什么会报错？？

### ISSUE THREAD

**Issue by mant7s** [chekun/laravel4sae#20]
Parse error: syntax error, unexpected '[' in vendor/laravel/framework/src/Illuminate/Support/helpers.php on line 426

求指教！！！

**Comment by chekun** [comment]
php版本低了，L4.2+只支持php4+，所以sae上是用不了的

**Comment by mant7s** [comment]
那有什么解决方法吗？？

**Comment by chekun** [comment]
用Laravel4.1.x或者不在SAE上用。
