### ISSUE TITLE
现在sae新建应用支持php5.6了 有计划做 laravel5 for sae吗

### ISSUE THREAD

**Issue by gantoday** [chekun/laravel4sae#22]
建议更新laravel5版
sae马上全面支持php5.6了
现在新建应用已经可以选择5.6 版本

**Comment by chekun** [comment]
有空的时候我可以更新下。嘿嘿。

**Comment by yuvista** [comment]
终于可以松口气了，被低版本坑的不行

**Comment by chekun** [comment]
@gantoday  @yuvista 很不幸，SAE限制了putenv() 方法，而Laravel5用了 https://github.com/vlucas/phpdotenv 包，这个包使用的env的相关方法。

:cry: :cry: :cry:

**Comment by gantoday** [comment]
@chekun 没救了？ 真是令人心碎

**Comment by yuvista** [comment]
自己写个假的putenv方法  不知道能不能行 不去修改系统参数

**Comment by chekun** [comment]
@yuvista 非也，无法写putenv函数 函数重定义

**Comment by PengFTang** [comment]
看到saebbs上有人已经实现了，所以应该是可以规避掉这个问题。sae帖子：http://saebbs.com/forum.php?mod=viewthread&tid=36474&highlight=laravel

**Comment by chekun** [comment]
@PengFTang  他的实现没有放出，应该是通过hack https://github.com/vlucas/phpdotenv 这个项目来绕过这个问题，我的想法是不想太多改造实现迁移，过份麻烦的话，不如不用SAE了，哈哈。
PS： 的项目名是 laravel 4(for) sae, 并不是只会让L4兼容，5.x有好的方案也会去做的。我自己的项目已经迁移到自己的VPS。SAE这种限制还是太多了。
