### ISSUE TITLE
如何确认 laravel4sae 中内嵌的 laravel 的版本？

### ISSUE THREAD

**Issue by g8up** [chekun/laravel4sae#23]
我在几个月前在 sae 部署了楼主的成果，现在想在本地搭建一个相应 laravel 的版本。
目前无法确认我之前所部署的 laravel4sae 中内嵌的 laravel 的版本，请库主指教~
thx！

**Comment by chekun** [comment]
你可以在目录下执行

```
php artisan -V
```

或者打开文件：`vendor/laravel/framework/src/Illuminate/Foundation/Application.php`

找到 const VERSION = '版本号'; 一行查看到。

**Comment by g8up** [comment]
未见那个文件路径。
我全局搜“Version”发现`1/bin/paths.php`文件头部注释里有

```
/**
 * Laravel - A PHP Framework For Web Artisans
 *
 * @package  Laravel
 * @version  3.2.13
 * @author   Taylor Otwell <taylorotwell@gmail.com>
 * @link     http://laravel.com
 */
```

应该能确认这个 laravel4sae 中内嵌的 laravel 的版本 是 3.2.13吧。
工程目录：
![laravel4sae-project-path](https://cloud.githubusercontent.com/assets/8005686/12134926/9023fb72-b46f-11e5-9592-5872fc76057e.png)

**Comment by chekun** [comment]
你的Laravel是3.xx系列的，我的这个库是给4.xx使用的，所以你这个不是根据我的文档迁移到SAE的， :laughing:
