### ISSUE TITLE
完全按照说做了，还是没法访问内容，求指点

### ISSUE THREAD

**Issue by liangqikang** [chekun/laravel4sae#5]
Laravel 4.1.18 , 本地安装调试正常，想移植到sae，按照作者的说明，一步步做了：
1、composer require chekun/laravel4sae ~1.0.0
2、按照HOW-TO.md里面的说明修改配置文件
3、php artisan sae:patch
4、打包上传

上传之后，发现router里的url访问，除了"/"，其他的都是404

Route::get('/', 'HomeController@showWelcome');
Route::get('/users', 'HomeController@showWelcome');

Route::get('/menu', 'OrderController@showMenu');
Route::get('/order', 'OrderController@order');
Route::get('/createorder', 'OrderController@createOrder');

弄了半天，实在不知道哪里出的问题，求指点~~

**Comment by chekun** [comment]
不知道你的url rewite规则如何写的？提供一下吧

**Comment by chekun** [comment]
PS: 你还需要试用1.0.1版本的，1.0.0对于laravel4.0.*有效。

**Comment by liangqikang** [comment]
url rewrite规则如下：
- rewrite: if(path ~ "^(.*)$") goto "/public/$1"

关键是我直接访问public/，可以访问到内容，但是，除此之外的别的路由规则，都是404了。
这是我的一个版本，是试的1.0.1的，不知道该怎么弄了。。
http://3.mbar.sinaapp.com/public/

**Comment by chekun** [comment]
@liangqikang 你这规则不行

你参考我的吧

```
  - rewrite: if (path ~ "^/$") goto "public/index.php"
  - rewrite: if (path ~ "^/robots.txt$") goto "public/robots.txt"
  - rewrite: if (path ~ "^/favicon.ico$") goto "public/favicon.ico"
  - rewrite: if (path ~ "^/static/(.*)$") goto "public/static/$1" 
  - rewrite: if(!is_dir() && !is_file() && path~"^(.*)$") goto "public/index.php/$1"
```

**Comment by liangqikang** [comment]
果然是。。按照上面的规则配置了就可以访问Routes了。。。谢谢啦。 

不过还有下面报错：
Error in exception handler: The stream or file "/data1/www/htdocs/144/mbar/3/app/storage/logs/laravel.log" could not be opened...

看起来是Log没权限？你是怎么处理的呢？

**Comment by chekun** [comment]
@liangqikang 目前该兼容包只是适配了基础的功能，其他的我本人暂无时间搞，也欢迎各位大牛贡献代码 :laughing:
