### ISSUE TITLE
改造LogServiceProvide

### ISSUE THREAD

**Issue by smallcode** [chekun/laravel4sae#8]
Laravel自带的Illuminate\Log\LogServiceProvide，会保存日志到app/storage/logs目录下。
SAE无法修改文件，因此会导致异常。
如果能改成将日志打印到SAE的日志中心就好了。

@chekun 请你帮忙改造一下，可以吗？

**Comment by chekun** [comment]
OK, 有时间会搞一下，你也可以搞搞，给我pull 回来哈

**Comment by chekun** [comment]
@smallcode 

这个我已经调研过了，只需曾一个SaeLogHandler类和扩展一下Illuminate\Log\Writer 和 Illuminate\Log\LogServiceProvider 就可以了。

周末有空我就做一下。

**Comment by chekun** [comment]
@smallcode 
适配过程可以参见： http://me.dilicms.com/open-source-projects/laravel4sae-support-sae-log-since-v1-1-0.html

**Comment by smallcode** [comment]
赞！谢谢！
